# Generated by Django 5.0.3 on 2024-04-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='final_timeslot_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='final_timeslot_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
