# Generated by Django 5.0.3 on 2024-03-13 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Friends'), (2, 'Pending'), (3, 'Rejected'), (4, 'Blocked')])),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userA_contacts', to=settings.AUTH_USER_MODEL)),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userB_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userA', 'userB')},
            },
        ),
    ]
